'use client'

import { useQuery } from '@tanstack/react-query'
import { getAnalyticsOverview } from '@/services/campaigns-api'
import { usePlanGate } from '../lib/entitlements'
import type { AnalyticsOverview } from '@/types/analytics'
import type { ActivityEvent } from '@/types/campaign'

/**
 * Inbox data — real sources only, no fabricated metrics.
 *   Executive summary  ← AnalyticsOverview (active_campaigns, awaiting_review, funnel)
 *   Priority queue      ← pending agent recommendations (lib/api/hooks)
 *   Activity feed       ← global activity (lib/api/hooks useRecentActivity)
 * Derivations here are pure so screens can memoize them.
 */
export const inboxKeys = {
  analytics: ['hl', 'inbox', 'analytics'] as const,
}

/**
 * The summary's data source, WHICH IS NOT FREE.
 *
 * `GET /analytics/overview` carries `require_entitlement("advanced_analytics")`
 * — a Pro capability — plus a `usage.view` permission check. The Inbox is the
 * landing route for every signed-in user on every plan, so this fires for every
 * Free and Plus organization and every brand-new signup, and comes back 402.
 *
 * Two things were wrong with that. The visible one is covered by
 * `summaryStats` below. The quieter one is that a denial is an ENFORCEMENT
 * EVENT: the server records one every time, so the audit log filled with
 * entitlement denials generated by a screen the customer merely opened.
 *
 * So the query WAITS for the gate and is never sent to an organization the
 * gate has resolved as denied.
 *
 * Waiting is the part that was wrong at first. The original version fired while
 * the gate was still `loading`, on the reasoning that withholding a request on
 * a guess is how a paying customer gets locked out of something they bought.
 * That reasoning is sound and it does not apply here: deferring until the gate
 * resolves is not a guess, it is a few hundred milliseconds. Browser QA caught
 * the difference — every hard load of the Inbox on a Free organization still
 * produced a 402, react-query retried it, and each attempt recorded another
 * enforcement event. The visible half of the fix worked; this half did not.
 *
 * An `error` state still fires. There the server genuinely is the authority and
 * we have no idea what the plan allows, so asking and being refused is better
 * than assuming.
 */
export function useInboxAnalytics(): { data?: AnalyticsOverview; isLoading: boolean } {
  const plan = usePlanGate('advanced_analytics')
  const pending = plan.state === 'loading'
  const denied = plan.state === 'denied'

  const query = useQuery<AnalyticsOverview>({
    queryKey: inboxKeys.analytics,
    queryFn: () => getAnalyticsOverview(),
    staleTime: 60_000,
    enabled: !pending && !denied,
  })

  // The gate's own load counts as loading. Without this the strip renders its
  // em dashes for a beat and then swaps to real numbers, which reads as a
  // failure that repaired itself — worse than the skeleton it replaced.
  return { data: query.data, isLoading: pending || query.isLoading }
}

export interface SummaryStat {
  label: string
  /**
   * The count, or NULL when it is not known.
   *
   * Null is not a styling detail, it is the whole point. This used to coalesce
   * every absent field to `0`, so an organization whose plan does not include
   * the analytics endpoint — which is every Free and Plus customer — opened the
   * product to "Open roles 0 · Awaiting review 0 · Interviews pending 0 ·
   * Offers outstanding 0" while their pipeline was full.
   *
   * That is the failure the standing rules call out twice: loading, error,
   * allowed and denied are four distinct states, and a confident wrong number
   * is worse than no number because the reader cannot tell it apart from a real
   * one. `QuotaMeter` refuses to render for exactly this reason; the summary
   * strip was doing the opposite three inches above it.
   */
  value: number | null
  href: string
}

/**
 * The four navigation summaries (not analytics).
 *
 * Returns `null` counts rather than zeros when the overview is unavailable —
 * denied, failed or still loading. The strip keeps rendering because it is
 * navigation and those destinations are useful regardless; it just stops
 * claiming to know how much is behind each one.
 */
export function summaryStats(a: AnalyticsOverview | undefined): SummaryStat[] {
  const known = a !== undefined
  const funnel = a?.charts.hiring_funnel ?? []
  // A stage missing from the funnel genuinely IS zero — the server returned the
  // funnel and that stage was not in it. Unknown and zero are only conflated
  // when the whole response is absent, which is what `known` distinguishes.
  const stage = (s: string) =>
    known ? (funnel.find((f) => f.stage.toLowerCase().includes(s))?.count ?? 0) : null
  return [
    {
      label: 'Open roles',
      value: known ? (a?.overview.active_campaigns ?? 0) : null,
      href: '/jobs',
    },
    {
      label: 'Awaiting review',
      value: known ? (a?.action_center.awaiting_review_count ?? 0) : null,
      href: '/jobs',
    },
    { label: 'Interviews pending', value: stage('interview'), href: '/jobs' },
    { label: 'Offers outstanding', value: stage('offer'), href: '/jobs' },
  ]
}

/** Candidates the AI flags for immediate review (drives the single AI line). */
export function aiReviewCount(a: AnalyticsOverview | undefined): number {
  return a?.ai_insights.candidates_requiring_review_count ?? 0
}

export interface ActivityGroup {
  label: string
  events: ActivityEvent[]
}

function dayBucket(iso: string | undefined): 'today' | 'yesterday' | 'earlier' {
  if (!iso) return 'earlier'
  const t = new Date(iso).getTime()
  if (Number.isNaN(t)) return 'earlier'
  const now = new Date()
  const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime()
  if (t >= startOfToday) return 'today'
  if (t >= startOfToday - 86_400_000) return 'yesterday'
  return 'earlier'
}

/** Group the feed into Today / Yesterday / Earlier (empty groups omitted). */
export function groupActivity(events: ActivityEvent[]): ActivityGroup[] {
  const buckets: Record<'today' | 'yesterday' | 'earlier', ActivityEvent[]> = {
    today: [],
    yesterday: [],
    earlier: [],
  }
  for (const e of events) buckets[dayBucket(e.created_at)].push(e)
  const order: Array<['today' | 'yesterday' | 'earlier', string]> = [
    ['today', 'Today'],
    ['yesterday', 'Yesterday'],
    ['earlier', 'Earlier'],
  ]
  return order.filter(([k]) => buckets[k].length > 0).map(([k, label]) => ({ label, events: buckets[k] }))
}
