"""Export the plan catalog to the JSON artifact the frontend mirror is tested against.

The frontend keeps a hand-written presentation mirror of this catalog
(`components/hirelens/lib/entitlements/catalog.ts`) for the same reason
`permissions.ts` mirrors `rbac.py`: the UI needs literal types and copy at build
time, not a runtime fetch. A hand-written mirror drifts, so both sides are pinned
to this generated file — `test_catalog_snapshot_parity.py` asserts the artifact
matches the live catalog, and `tests/entitlements-catalog.test.ts` asserts the
mirror matches the artifact. Drift on either side is a failing test rather than a
wrong price on a lock surface.

The `v1` ruleset is exported: it is the plan matrix the product presents. The
`founding` set is not presentation — a grandfathered organization sees no locks
at all, so there is nothing for it to render.

Run after ANY edit to app/enterprise/catalog.py:

    cd backend && .venv/Scripts/python.exe -m scripts.export_catalog_snapshot
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from app.enterprise.catalog import RULESET_V1, catalog_snapshot

#: backend/scripts/ -> repo root -> the frontend entitlements module.
ARTIFACT = (
    Path(__file__).resolve().parents[2]
    / "frontend"
    / "components"
    / "hirelens"
    / "lib"
    / "entitlements"
    / "catalog.snapshot.json"
)

_HEADER = {
    "_comment": (
        "GENERATED by backend/scripts/export_catalog_snapshot.py from "
        "app/enterprise/catalog.py. Do not edit by hand. The server is the "
        "authority on entitlement; this file carries presentation data only."
    ),
    "ruleset": RULESET_V1,
}


def render() -> str:
    """The exact bytes the artifact should contain, so callers can compare."""
    payload = {**_HEADER, **catalog_snapshot(ruleset=RULESET_V1)}
    return json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def main() -> int:
    content = render()
    if not ARTIFACT.parent.exists():
        print(f"target directory does not exist: {ARTIFACT.parent}", file=sys.stderr)
        return 1
    previous = ARTIFACT.read_text(encoding="utf-8") if ARTIFACT.exists() else None
    if previous == content:
        print(f"catalog snapshot already up to date: {ARTIFACT}")
        return 0
    ARTIFACT.write_text(content, encoding="utf-8")
    print(f"{'updated' if previous else 'created'}: {ARTIFACT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
