"""
Customers interact with Hirevo, not the LLM vendor underneath it.

`GAB-D1` found `"Powered by Groq LLM"` printed on the footer of every exported
PDF, with `author="AI Resume Intelligence Platform"` in the document metadata.
Both had shipped for months. **The whole backend suite stayed green through the
fix, because nothing had ever asserted on either string** — which is also why
nobody caught it: there was no failing signal, only a line nobody re-read.

This file is that signal. It guards one rule:

    No customer-visible exported artifact names the model vendor.

Two independent reasons, and the second is the one that outlives the governance
rule:

1. Naming the supplier on an artifact presents a procurement choice as a quality
   signal (Checklist §8.9, **Gate 2** — a gate failure is unscorable, not
   low-scoring).
2. **It is a claim that goes stale on its own.** Provider selection is
   configuration (`app/ai/gateway/`), with a fallback chain and a runtime
   switch, so the vendor that answered is not knowable when the template is
   written. A PDF outlives the request that made it and cannot be corrected
   once it has been sent.

## Scope — deliberately narrow

This tests **rendered artifacts**, not the repository. `Groq` is referenced
legitimately and often: the provider adapter, `GROQ_API_KEY`, the model
registry, ADR-002, the docs, and the skills taxonomy (candidates list Groq on
their résumés — `app/nlp/skill_normalizer.py`). A repo-wide ban would be wrong
and would be deleted the first time it fired.

Nor is this a snapshot: it asserts what must be **absent** and the one line that
must be **present**, so wording, layout and content stay free to change.

## Why the denylist is safe here and would not be at runtime

`_VENDOR` includes `claude` and `gemini`, which are also human names — a real
candidate called Claude would trip it. That is fine, because it is only ever
applied to a **fixture we control**. This is a build-time guard on the
*template*, never a filter on customer data.

Runnable under pytest, or standalone:  python -m pytest tests/test_export_attribution.py
"""
from __future__ import annotations

import re

import fitz  # PyMuPDF — already a dependency (app/parser/pdf.py)
import pytest

from app.services import report_generator
from app.services.report_generator import generate_match_report, generate_report

# The line every export must carry. Asserted positively so that *deleting* the
# footer — the lazy way to make an absence-test pass — fails too.
REQUIRED_FOOTER = "Generated by Hirevo"
REQUIRED_AUTHOR = "Hirevo"

#: Model vendors and the phrasing that turns one into a quality signal. Word
#: boundaries, so "Gemini" does not match inside an unrelated word.
_VENDOR = re.compile(
    r"\b(groq|openai|anthropic|claude|gemini|llama|mistral|moonshot|kimi|"
    r"openrouter|gpt|powered\s+by)\b",
    re.IGNORECASE,
)

# Deliberately bland: nothing here should trip _VENDOR on its own, so a hit is
# always the template's doing and never the fixture's.
RESUME = {"name": "Test Candidate", "email": "candidate@example.test", "phone": "+91-00000-00000"}

ANALYSIS = {
    "ats_score": 78,
    "score_breakdown": {"keywords": 20, "formatting": 18, "experience": 22, "skills": 18},
    "summary": "Experienced backend engineer.",
    "strengths": ["Distributed systems", "Data modelling"],
    "weaknesses": ["Limited frontend exposure"],
    "recommendations": ["Quantify outcomes"],
    "recommended_roles": ["Backend Engineer"],
}

MATCH = {
    "match_score": 71,
    "matching_skills": ["Python", "PostgreSQL"],
    "missing_skills": ["Kubernetes"],
    "candidate_strengths": ["Depth in backend work"],
    "areas_for_improvement": ["Container orchestration"],
    "hiring_recommendation": "Interview",
    "recommendation_explanation": "Solid core match.",
    "relevant_projects": ["Payments service"],
    "less_relevant_projects": [],
    "experience_relevance": "High",
}

#: (label, callable) for every exporter a customer can receive. `TestEveryExporterIsCovered`
#: fails if `report_generator` grows one that is not in here.
EXPORTERS = [
    ("ATS report", lambda: generate_report(ANALYSIS, RESUME)),
    ("Match report", lambda: generate_match_report(MATCH, RESUME)),
]


def _read(pdf: bytes) -> tuple[str, dict[str, str]]:
    """Rendered text and document metadata — the two things a customer can see.

    Metadata matters as much as the page: `author=` is what a PDF reader shows
    in Properties, and it is where GAB-D1's violation would most plausibly be
    *relocated* by someone who read the rule as being about the footer only.
    """
    doc = fitz.open(stream=pdf, filetype="pdf")
    try:
        text = "\n".join(page.get_text() for page in doc)
        meta = {k: str(v) for k, v in (doc.metadata or {}).items() if v}
        return text, meta
    finally:
        doc.close()


@pytest.mark.parametrize("label,render", EXPORTERS, ids=[e[0] for e in EXPORTERS])
class TestNoVendorAttribution:
    def test_rendered_page_names_no_vendor(self, label, render):
        text, _ = _read(render())
        hit = _VENDOR.search(text)
        assert hit is None, (
            f"{label}: the rendered PDF names '{hit.group(0)}' — a customer-visible "
            f"model-vendor attribution (GAB-D1, Checklist §8.9 Gate 2)."
            if hit else ""
        )

    def test_document_metadata_names_no_vendor(self, label, render):
        _, meta = _read(render())
        blob = "\n".join(f"{k}={v}" for k, v in meta.items())
        hit = _VENDOR.search(blob)
        assert hit is None, (
            f"{label}: PDF metadata names '{hit.group(0)}'. The vendor attribution "
            f"must be REMOVED, not relocated — metadata is customer-visible in a "
            f"reader's Properties pane."
            if hit else ""
        )

    def test_carries_the_neutral_hirelens_attribution(self, label, render):
        text, meta = _read(render())
        assert REQUIRED_FOOTER in text, (
            f"{label}: expected the footer to read '{REQUIRED_FOOTER} • Confidential'. "
            f"Deleting the footer is not how this file is satisfied."
        )
        assert meta.get("author") == REQUIRED_AUTHOR, (
            f"{label}: document author is {meta.get('author')!r}, expected {REQUIRED_AUTHOR!r}."
        )


@pytest.mark.parametrize("label,render", EXPORTERS, ids=[e[0] for e in EXPORTERS])
class TestExportIdentity:
    """Every page carries the shared Hirevo export identity: the diagonal
    watermark painted behind the content and the per-page footer, both drawn by
    `_paint_page_brand` via onFirstPage/onLaterPages. Asserted per page, not per
    document — a multi-page report with a branded first page only is exactly the
    failure the shared hook exists to prevent."""

    def test_every_page_carries_watermark_and_footer(self, label, render):
        doc = fitz.open(stream=render(), filetype="pdf")
        try:
            assert doc.page_count >= 1
            for number, page in enumerate(doc, start=1):
                text = page.get_text()
                assert report_generator.WATERMARK_TEXT in text, (
                    f"{label}: page {number} is missing the '{report_generator.WATERMARK_TEXT}' watermark."
                )
                expected = report_generator.PAGE_FOOTER_TEXT.format(page=number)
                assert expected in text, (
                    f"{label}: page {number} is missing the footer {expected!r}."
                )
        finally:
            doc.close()

    def test_watermark_and_footer_name_no_vendor(self, label, render):
        # The identity strings themselves must obey the GAB-D1 rule.
        blob = f"{report_generator.WATERMARK_TEXT}\n{report_generator.PAGE_FOOTER_TEXT}"
        assert _VENDOR.search(blob) is None


class TestEveryExporterIsCovered:
    """The guard is only worth what it covers.

    A `generate_comparison_report` added next quarter would inherit the footer
    by copy-paste and be tested by nothing. This fails the moment
    `report_generator` grows a public exporter that `EXPORTERS` does not name,
    so the next person is told rather than trusted to remember.
    """

    def test_no_untested_exporter_exists(self):
        public = {
            name for name in dir(report_generator)
            if name.startswith("generate_") and callable(getattr(report_generator, name))
        }
        covered = {"generate_report", "generate_match_report"}
        missing = public - covered
        assert not missing, (
            f"report_generator exposes untested exporter(s): {sorted(missing)}. "
            f"Add each to EXPORTERS — a customer-facing artifact with no attribution "
            f"guard is how GAB-D1 happened."
        )


class TestTheGuardActuallyBites:
    """Proof the assertions are not vacuous.

    This mirrors how the billing boundaries were proven — by injecting a
    violation and watching the guard fail. Without it, a `_read` that silently
    returned an empty string would make every test above pass while the footer
    said anything at all.
    """

    def test_scanner_catches_the_exact_string_gab_d1_removed(self):
        assert _VENDOR.search("Generated by Hirevo  •  Powered by Groq LLM  •  Confidential")

    def test_scanner_catches_a_vendor_moved_into_metadata(self):
        assert _VENDOR.search("author=Hirevo (OpenAI)")

    def test_scanner_passes_the_line_we_actually_ship(self):
        assert _VENDOR.search("Generated by Hirevo  •  Confidential") is None

    def test_extraction_returns_real_content(self):
        # If this ever returns nothing, the absence-tests above are meaningless.
        text, meta = _read(generate_report(ANALYSIS, RESUME))
        assert "Confidential" in text and meta.get("author")
