"""
Copilot ↔ Agent bridge.

Lets the Recruiter Copilot answer proactive questions ("what needs my attention
today?", "any bottlenecks?", "which campaign is at risk?") by reusing the SAME
agent engine (`services.agent_service`) — no duplicated logic. Reads open
recommendations (running a scan only if none exist yet) and renders the agent's
briefing + top items into a `CopilotStructuredResponse`.

Executive scope only (no specific candidate selected); returns None otherwise.
"""

from __future__ import annotations

import logging
from typing import Any, Optional

from app.ai.agent import agent_engine
from app.schemas.agent import AgentScanResponse
from app.schemas.copilot import CopilotPageContext, CopilotSource, CopilotStructuredResponse
from app.services.agent_service import list_recommendations, run_agent_scan

logger = logging.getLogger(__name__)

_TRIGGERS = (
    "needs my attention", "need my attention", "what should i", "anything i should",
    "bottleneck", "urgent", "priorit", "at risk", "attention today", "what's on fire",
    "whats on fire", "action items", "recommended actions", "what needs doing", "the agent",
)


def _is_agent(question: str) -> bool:
    q = f" {question.lower()} "
    return any(t in q for t in _TRIGGERS)


def try_agent(
    question: str,
    page: CopilotPageContext,
    *,
    agent_repo: Any,
    campaign_repo: Any,
    candidate_repo: Any,
    note_repo: Any,
    analytics_repo: Any,
    activity_repo: Any,
    embedding_repo: Any,
) -> Optional[tuple[AgentScanResponse, CopilotStructuredResponse]]:
    if page.candidate_id or not _is_agent(question):
        return None

    open_recs = list_recommendations(agent_repo=agent_repo, status="pending")
    if open_recs:
        briefing = agent_engine.briefing(open_recs)
        result = AgentScanResponse(generated=0, total_open=len(open_recs), recommendations=open_recs, briefing=briefing)
    else:
        result = run_agent_scan(
            agent_repo=agent_repo, campaign_repo=campaign_repo, candidate_repo=candidate_repo,
            note_repo=note_repo, analytics_repo=analytics_repo, activity_repo=activity_repo,
            embedding_repo=embedding_repo,
        )
    return result, _render(result)


def safe_try_agent(question, page, agent_repo, campaign_repo, candidate_repo, note_repo, analytics_repo, activity_repo, embedding_repo):
    """try_agent that never raises — the copilot must never break on this."""
    try:
        return try_agent(
            question, page, agent_repo=agent_repo, campaign_repo=campaign_repo, candidate_repo=candidate_repo,
            note_repo=note_repo, analytics_repo=analytics_repo, activity_repo=activity_repo, embedding_repo=embedding_repo,
        )
    except Exception as exc:  # pragma: no cover
        logger.info("Copilot agent skipped: %s", exc)
        return None


def _render(result: AgentScanResponse) -> CopilotStructuredResponse:
    recs = result.recommendations
    if not recs:
        return CopilotStructuredResponse(
            answer="Nothing urgent right now — your pipeline looks clear. I'll keep watching.",
            confidence=60, reasoning_summary="No open agent recommendations.",
            sources_used=[CopilotSource(source="Autonomous Agent")],
            followups=["Run a full agent scan", "Summarize this campaign"],
        )
    b = result.briefing
    lines: list[str] = []
    if b and b.headline:
        lines.append(f"**{b.headline}**")
    lines.append("\n**What needs your attention**")
    for r in sorted(recs, key=lambda x: {"urgent": 0, "high": 1, "medium": 2, "low": 3}.get(x.severity, 4))[:6]:
        lines.append(f"- _({r.severity})_ {r.title}")
    return CopilotStructuredResponse(
        answer="\n".join(lines),
        summary=(b.summary if b else "") or f"{len(recs)} open recommendation(s).",
        recommendations=[r.recommended_action for r in recs[:5] if r.recommended_action],
        confidence=70,
        reasoning_summary="Generated by the shared Autonomous Recruiting Agent.",
        followups=["Which campaign is most at risk?", "Show urgent candidates", "Any interview bottlenecks?"],
        sources_used=[CopilotSource(source="Autonomous Agent", detail=f"{len(recs)} open recommendations")],
    )
