"""
Pydantic schemas for JD-Resume match analysis.

GroqMatchAnalysis validates the qualitative output from Groq.
MatchAnalysisResponse is the final response combining deterministic
scoring with Groq's recruiter intelligence.
"""

from pydantic import BaseModel, Field


class GroqMatchAnalysis(BaseModel):
    """
    Schema to validate the qualitative analysis returned by Groq.
    Groq identifies skills, relevance, and recommendations.
    Numeric scores are NOT generated by Groq — they are computed
    deterministically by the backend match scorer.
    """
    matching_skills: list[str] = Field(description="Skills present in both JD and resume")
    missing_skills: list[str] = Field(description="Skills required by JD but absent from resume")
    experience_relevance: str = Field(description="Evaluation of experience-role alignment")
    relevant_projects: list[str] = Field(description="Projects that directly support JD requirements")
    less_relevant_projects: list[str] = Field(description="Projects with limited JD relevance")
    candidate_strengths: list[str] = Field(description="Recruiter-focused strengths (3-5 items)")
    areas_for_improvement: list[str] = Field(description="Constructive gaps and missing requirements (2-4 items)")
    hiring_recommendation: str = Field(
        description="One of: Strongly Recommend Interview, Recommend Interview, "
                    "Consider for Further Review, Not Recommended"
    )
    recommendation_explanation: str = Field(description="Short explanation supporting the hiring recommendation")


class MatchAnalysisResponse(BaseModel):
    """
    Final match analysis response combining deterministic scoring
    with Groq-generated recruiter intelligence.
    """
    analysis_version: str = Field(default="v1.1", description="Version of the analysis engine")
    job_match_score: int = Field(default=0, ge=0, le=100, description="Deterministic job match score (0-100)")
    match_category: str = Field(default="Weak Match", description="Excellent / Strong / Moderate / Weak Match")

    matching_skills: list[str] = Field(default_factory=list, description="Skills present in both JD and resume")
    missing_skills: list[str] = Field(default_factory=list, description="Skills required by JD but not in resume")
    experience_relevance: str = Field(default="", description="Experience-role alignment evaluation")
    relevant_projects: list[str] = Field(default_factory=list, description="Projects supporting JD requirements")
    less_relevant_projects: list[str] = Field(default_factory=list, description="Projects with limited JD relevance")
    candidate_strengths: list[str] = Field(default_factory=list, description="Recruiter-focused strengths")
    areas_for_improvement: list[str] = Field(default_factory=list, description="Constructive gaps")
    hiring_recommendation: str = Field(default="", description="Hiring recommendation category")
    recommendation_explanation: str = Field(default="", description="Explanation for the recommendation")
