import { describe, it, expect } from 'vitest'
import snapshot from '../components/hirelens/lib/entitlements/catalog.snapshot.json'
import {
  CAMPAIGN_CANDIDATE_LIMITS,
  CORE_PLAN_KEYS,
  FEATURES,
  FEATURE_KEYS,
  LIMITS,
  METRIC_KEYS,
  PLAN_KEYS,
  PLAN_LABELS,
  RESUME_WINDOW,
  TRIAL_PLAN_KEYS,
  UNLIMITED,
  featuresByTier,
  featuresForPlan,
  isAtLeast,
  metricLabel,
  metricWindow,
  minimumPlanForLimit,
  nextPlanWithMoreOf,
  normalizePlan,
  planLabel,
  upgradeCta,
  upgradeTargetFor,
  type MetricKey,
  type PlanKey,
} from '../components/hirelens/lib/entitlements/catalog'

/**
 * Frontend half of the catalog parity contract.
 *
 * `catalog.snapshot.json` is generated by the backend from
 * `app/enterprise/catalog.py`; `test_catalog_snapshot_parity.py` guarantees it
 * is not stale. So comparing the hand-written mirror against the artifact is
 * comparing it against the live server catalog, one hop removed.
 *
 * This is what stops the mirror going quietly wrong. A drifted label or
 * `min_plan` breaks nothing at runtime — it just shows a customer the wrong
 * feature name, or sends them to buy the wrong tier. Nothing else would catch
 * that before they did.
 *
 * If this fails after a backend catalog change, update `catalog.ts` to match.
 * The server always wins.
 */

type SnapshotFeature = { key: string; label: string; min_plan: string; blurb: string }
type SnapshotPlan = {
  key: string
  label: string
  rank: number
  limits: Record<string, number>
  resume_window: string
  metric_windows: Record<string, string>
  campaign_candidates: number
  features: string[]
}

const snapFeatures = snapshot.features as SnapshotFeature[]
const snapPlans = snapshot.plans as SnapshotPlan[]
const snapMetrics = snapshot.metrics as Record<string, string>

describe('catalog parity: plans', () => {
  it('mirrors the plan keys, in the same order', () => {
    expect(PLAN_KEYS).toEqual(snapPlans.map((p) => p.key))
  })

  it('mirrors the plan ranks, so tier comparison agrees with the server', () => {
    for (const plan of snapPlans) {
      expect(PLAN_KEYS.indexOf(plan.key as PlanKey)).toBe(plan.rank)
    }
  })

  it('mirrors the plan labels', () => {
    for (const plan of snapPlans) {
      expect(PLAN_LABELS[plan.key as PlanKey]).toBe(plan.label)
    }
  })

  it('mirrors every limit, including the unlimited sentinel', () => {
    for (const plan of snapPlans) {
      expect(LIMITS[plan.key as PlanKey]).toEqual(plan.limits)
    }
  })

  it('mirrors the résumé window — trials are lifetime, everything else monthly', () => {
    for (const plan of snapPlans) {
      expect(RESUME_WINDOW[plan.key as PlanKey]).toBe(plan.resume_window)
    }
    expect(RESUME_WINDOW.free).toBe('month')
    expect(RESUME_WINDOW.trial).toBe('lifetime')
    expect(RESUME_WINDOW.trial_interview).toBe('lifetime')
  })

  it('mirrors the per-campaign candidate caps', () => {
    for (const plan of snapPlans) {
      expect(
        CAMPAIGN_CANDIDATE_LIMITS[plan.key as PlanKey],
        `campaign_candidates for ${plan.key}`,
      ).toBe(plan.campaign_candidates)
    }
  })

  it('mirrors the metered windows', () => {
    for (const plan of snapPlans) {
      for (const [metric, window] of Object.entries(plan.metric_windows)) {
        expect(
          metricWindow(metric as MetricKey, plan.key as PlanKey),
          `${metric} window on ${plan.key}`,
        ).toBe(window)
      }
    }
  })
})

describe('catalog parity: features', () => {
  it('has exactly the server\'s feature keys — no extras, none missing', () => {
    expect([...FEATURE_KEYS].sort()).toEqual(snapFeatures.map((f) => f.key).sort())
  })

  it('mirrors every label, min_plan and blurb', () => {
    for (const f of snapFeatures) {
      const mine = FEATURES[f.key as keyof typeof FEATURES]
      expect(mine, `missing feature ${f.key}`).toBeDefined()
      expect(mine.label, `label for ${f.key}`).toBe(f.label)
      expect(mine.minPlan, `min_plan for ${f.key}`).toBe(f.min_plan)
      expect(mine.blurb, `blurb for ${f.key}`).toBe(f.blurb)
    }
  })

  it('derives the same per-plan feature sets the server does', () => {
    for (const plan of snapPlans) {
      const mine = featuresForPlan(plan.key as PlanKey)
        .map((f) => f.key)
        .sort()
      expect(mine, `features for ${plan.key}`).toEqual([...plan.features].sort())
    }
  })

  it('groups every feature under exactly one introducing tier', () => {
    const grouped = featuresByTier().flatMap((t) => t.features.map((f) => f.key))
    expect(grouped.sort()).toEqual([...FEATURE_KEYS].sort())
  })
})

describe('catalog parity: metrics', () => {
  it('mirrors the metric keys and their labels', () => {
    // The snapshot carries the org metrics plus the per-campaign candidate cap,
    // which is deliberately not an org metric on this side.
    expect([...METRIC_KEYS, 'campaign_candidates'].sort()).toEqual(
      Object.keys(snapMetrics).sort(),
    )
    for (const [key, label] of Object.entries(snapMetrics)) {
      expect(metricLabel(key)).toBe(label)
    }
  })

  it('splits the plan list into the ladder and the trials, like the server', () => {
    expect([...CORE_PLAN_KEYS]).toEqual(snapshot.core_plans)
    expect([...TRIAL_PLAN_KEYS].sort()).toEqual([...snapshot.trial_plans].sort())
  })
})

describe('plan resolution', () => {
  it('never downgrades a legacy paid slug to free', () => {
    // A `business` row silently reading as Free would tell a paying customer to
    // upgrade to something they already bought. This is the single worst
    // failure this module can have.
    expect(normalizePlan('professional')).toBe('plus')
    expect(normalizePlan('business')).toBe('pro')
    expect(planLabel('business')).toBe('Pro')
  })

  it('resolves unknown, empty and mixed-case values sensibly', () => {
    expect(normalizePlan(undefined)).toBe('free')
    expect(normalizePlan('')).toBe('free')
    expect(normalizePlan('  PRO ')).toBe('pro')
    expect(normalizePlan('nonsense')).toBe('free')
  })

  it('orders tiers', () => {
    expect(isAtLeast('pro', 'plus')).toBe(true)
    expect(isAtLeast('plus', 'pro')).toBe(false)
    expect(isAtLeast('pro', 'pro')).toBe(true)
  })
})

describe('limit arithmetic', () => {
  it('finds the cheapest plan that covers a requirement', () => {
    expect(minimumPlanForLimit('resumes', 101)).toBe('plus') // Free stops at 100
    expect(minimumPlanForLimit('resumes', 201)).toBe('pro') // Plus stops at 200
    expect(minimumPlanForLimit('members', 2)).toBe('plus')
    expect(minimumPlanForLimit('members', 26)).toBe('enterprise')
    expect(minimumPlanForLimit('campaigns', 3)).toBe('plus') // unlimited on Plus
  })

  it('offers the next tier that grants MORE, not the one covering today', () => {
    // At 190 of 200 on Plus, the plan covering 191 is Plus — offering it would
    // sell a customer the plan they are already on. Pro is the real remedy.
    expect(nextPlanWithMoreOf('resumes', 'plus', 200)).toBe('pro')
    expect(nextPlanWithMoreOf('resumes', 'free', 100)).toBe('plus')
    expect(nextPlanWithMoreOf('members', 'plus', 3)).toBe('pro')
    expect(nextPlanWithMoreOf('members', 'pro', 25)).toBe('enterprise')
  })

  it('never offers a trial as the remedy for a running-low meter', () => {
    // The trials rank between Free and Plus but hold FEWER résumés than Free —
    // `nextPlanWithMoreOf` must skip past them to the first tier with more.
    expect(nextPlanWithMoreOf('resumes', 'free', 100)).toBe('plus')
    expect(LIMITS.trial.resumes).toBeLessThan(LIMITS.free.resumes)
  })

  it('offers nothing above an unlimited allowance, or when no tier gives more', () => {
    expect(nextPlanWithMoreOf('resumes', 'pro', UNLIMITED)).toBeNull()
    expect(nextPlanWithMoreOf('organizations', 'free', 1)).toBeNull()
    expect(nextPlanWithMoreOf('members', 'enterprise', UNLIMITED)).toBeNull()
  })

  it('respects a negotiated override rather than the catalog figure', () => {
    // An org on Plus with a 300-résumé deal must not be offered a tier that
    // would give it less than it already has.
    expect(nextPlanWithMoreOf('resumes', 'plus', 300)).toBe('pro') // pro is 700
    expect(nextPlanWithMoreOf('members', 'plus', 40)).toBe('enterprise') // pro caps at 25
  })

  it('has no answer for a second organization — multi-org is deferred in V1', () => {
    expect(minimumPlanForLimit('organizations', 2)).toBeNull()
    expect(LIMITS.enterprise.organizations).toBe(1)
  })

  it('treats -1 as unlimited everywhere it appears', () => {
    expect(LIMITS.pro.interview_packs).toBe(UNLIMITED)
    expect(minimumPlanForLimit('resumes', 10_000)).toBe('enterprise')
  })
})

describe('upgrade targets', () => {
  it('shows the tier the feature actually needs, not the first gate hit', () => {
    // A Free user reaching webhooks is refused by the Integrations router gate
    // first, which names Pro. Pro is a true next step but would not unlock
    // webhooks; upgrading on that advice buys the wrong plan.
    expect(upgradeTargetFor('pro', 'webhooks')).toBe('enterprise')
    expect(upgradeCta(upgradeTargetFor('pro', 'webhooks'))).toBe('Upgrade to Custom')
  })

  it('keeps the server target when the catalog agrees or knows less', () => {
    expect(upgradeTargetFor('pro', 'ai_copilot')).toBe('pro')
    expect(upgradeTargetFor('plus', 'unknown_feature')).toBe('plus')
    expect(upgradeTargetFor(null, 'ai_copilot')).toBe('pro')
    expect(upgradeTargetFor(null, null)).toBeNull()
  })

  it('never lowers the server\'s requirement', () => {
    // The catalog may raise the target for accuracy; lowering it would promise
    // access the server will refuse.
    expect(upgradeTargetFor('enterprise', 'ai_copilot')).toBe('enterprise')
  })

  it('derives its copy rather than hardcoding a tier', () => {
    expect(upgradeCta('plus')).toBe('Upgrade to Plus')
    expect(upgradeCta(null)).toBe('Upgrade')
  })
})
